package main;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * GUI initialised at startup.
 * @author JASEEN, Loki
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        Scale.setBounds(background, 0, 0, 100, 90);
        
        int originWidth = background.getIcon().getIconWidth();
        int originHeight = background.getIcon().getIconHeight();
        
        BufferedImage bufImg = new BufferedImage(background.getWidth(), background.getHeight(), BufferedImage.TYPE_INT_ARGB);
        
        Graphics2D graphics2D = bufImg.createGraphics();
        graphics2D.scale(background.getWidth() / (double)originWidth, background.getHeight() / (double)originHeight);
        
        background.getIcon().paintIcon(background,graphics2D,0,0);
        graphics2D.dispose();
        
        background.setIcon(new ImageIcon(bufImg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 750));
        getContentPane().setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GUI Base.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1735, 1050);
        background.getAccessibleContext().setAccessibleName("background");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    private ChartPanel polarChart;
    private ChartPanel sumWindspeedWeek;
    private ChartPanel sumWindspeedMonth;
    private ChartPanel sumWindspeedQuarter;
    private ChartPanel histogram;
    private ChartPanel avgWindspeed;
    
    public void initGraphs(JFreeChart polar,
            JFreeChart sumWindspeedWeekChart,
            JFreeChart sumWindspeedMonthChart,
            JFreeChart sumWindspeedQuarterChart,
            JFreeChart avgWindspeedChart,
            JFreeChart histogramChart) 
    {
        polarChart = new ChartPanel(polar);
        
        avgWindspeed = new ChartPanel(sumWindspeedWeekChart);
        
        sumWindspeedQuarter = new ChartPanel(sumWindspeedMonthChart);
        sumWindspeedMonth = new ChartPanel(sumWindspeedQuarterChart);
        sumWindspeedWeek = new ChartPanel(avgWindspeedChart);
        histogram = new ChartPanel(histogramChart);
        
        
        setupCharts();
                
        //this.removeAll();
                
        background.add(sumWindspeedWeek);        
        background.add(polarChart);
        background.add(sumWindspeedMonth);
        
        // posX posY width height
        
        Scale.setBounds(sumWindspeedWeek, 55, 17, 20, 21);
        Scale.setBounds(polarChart, 76.5, 17, 20, 21);
        Scale.setBounds(sumWindspeedMonth, 55, 40.5, 20, 21);
        //this.add(avgWindspeed);
        //this.add(histogram);
        //this.add(sumWindspeedQuarter);
        //this.add(sumWindspeedMonth);
        //this.add(sumWindspeedWeek);
        
    }
    
    /**
     * Initial setup of charts.
     */
    private void setupCharts() {                
        sumWindspeedWeek.setDomainZoomable(false);
        sumWindspeedWeek.setRangeZoomable(false);
        
        sumWindspeedMonth.setDomainZoomable(false);
        sumWindspeedMonth.setRangeZoomable(false);
        
        sumWindspeedQuarter.setDomainZoomable(false);
        sumWindspeedQuarter.setRangeZoomable(false);
        
        avgWindspeed.setDomainZoomable(false);
        avgWindspeed.setRangeZoomable(false);
        
        histogram.setDomainZoomable(false);
        histogram.setRangeZoomable(false);
        
        polarChart.setDomainZoomable(false);
        polarChart.setRangeZoomable(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables
}
